# Generated by Django 4.2.28 on 2026-02-24 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('website', models.URLField()),
                ('opportunities_url', models.URLField()),
                ('is_ivy_league', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/')),
                ('description', models.TextField(blank=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=500)),
                ('domains', models.JSONField(default=list)),
                ('opportunity_types', models.JSONField(default=list)),
                ('universities', models.JSONField(default=list)),
                ('frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('opportunity_type', models.CharField(choices=[('workshop', 'Workshop'), ('hackathon', 'Hackathon'), ('internship', 'Internship'), ('research', 'Research Position'), ('scholarship', 'Scholarship'), ('conference', 'Conference'), ('course', 'Course'), ('fellowship', 'Fellowship'), ('competition', 'Competition'), ('job', 'Job')], max_length=20)),
                ('domain', models.CharField(blank=True, choices=[('ai', 'Artificial Intelligence'), ('ml', 'Machine Learning'), ('ds', 'Data Science'), ('cs', 'Computer Science'), ('ece', 'Electrical & Computer Engineering'), ('mech', 'Mechanical Engineering'), ('bio', 'Biomedical'), ('chem', 'Chemistry'), ('physics', 'Physics'), ('math', 'Mathematics'), ('business', 'Business'), ('law', 'Law'), ('medicine', 'Medicine'), ('humanities', 'Humanities'), ('arts', 'Arts'), ('social_sciences', 'Social Sciences')], max_length=20, null=True)),
                ('external_url', models.URLField()),
                ('application_url', models.URLField(blank=True)),
                ('deadline', models.DateTimeField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_remote', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('stipend', models.CharField(blank=True, max_length=100)),
                ('eligibility_criteria', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('requirements', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('source_url', models.URLField()),
                ('source_id', models.CharField(blank=True, max_length=200)),
                ('source_hash', models.CharField(blank=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('applications_count', models.IntegerField(default=0)),
                ('saved_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='opportunities.university')),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_data', models.JSONField()),
                ('resume_used', models.FileField(upload_to='applications/resumes/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='applications/cover_letters/')),
                ('additional_documents', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('interview', 'Interview')], default='applied', max_length=20)),
                ('confirmation_email', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('interview', 'Interview')], default='saved', max_length=20)),
                ('applied_date', models.DateTimeField(blank=True, null=True)),
                ('application_data', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('reminder_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='opportuniti_user_id_7c1721_idx'), models.Index(fields=['reminder_date'], name='opportuniti_reminde_2c4131_idx')],
                'unique_together': {('user', 'opportunity')},
            },
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['domain', '-created_at'], name='opportuniti_domain_cf0fba_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['deadline'], name='opportuniti_deadlin_294f61_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['university', 'opportunity_type'], name='opportuniti_univers_9f35be_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['source_hash'], name='opportuniti_source__5830d6_idx'),
        ),
    ]
